---
# tasks file for casalibs-src
- name: Install apt dependencies.
  apt: name={{item}} update_cache=yes cache_valid_time=600
  with_items: casalibs_apt_deps
  sudo: yes
  tags: base apt


- name: Create repo dir with correct permissions
  file: path={{item}} state=directory mode=0755 owner={{ansible_user_id}}
  with_items:
    - "{{ casalibs_repo_prefix }}"
    - "{{ casalibs_install_prefix }}"
  sudo: yes

- include: casa_measures.yml tags=casa_measures
- include: get_casacore_github.yml tags=casacore
- include: build_casacore.yml tags=casacore
- include: casarest.yml tags=casarest
- include: python-casacore.yml tags=python-casacore

- include: python-casacore-venv.yml tags=python-casacore
  when: python_casacore_venv is defined

- name: Upload script to add casacore / casacore-python to path.
  template:
    src: "{{item}}"
    dest: "{{casalibs_install_prefix}}/{{item.split('.')[0]}}-{{casacore_version}}.sh"
    mode: 'ugo+r'
  with_items:
    - init-casalibs.j2
    - init-casabinaries.j2
  register:
    casacore_init_scripts
  tags: scripts

# Should just use src: item.dest, but this is broken because of issue
# https://github.com/ansible/ansible/issues/10190
- name: Add 'default' symlink to latest installed casacore inits
  file:
    src: "{{casalibs_install_prefix}}/{{item.item.split('.')[0]}}-{{casacore_version}}.sh"
    dest: "{{casalibs_install_prefix}}/{{item.item.split('.')[0]}}.sh"
    state: link
  with_items: casacore_init_scripts.results
  tags: scripts

- name: Check casalibs import OK
  shell: >
          . {{casalibs_install_prefix}}/init-casalibs.sh &&
            python -c "from casacore import measures,tables; print('A-OK');"
  changed_when: False
  tags: test

- name: Export casalibs_install_prefix to a 'host-fact' type variable
  set_fact:
    casalibs_install_prefix: "{{ casalibs_install_prefix }}"

