- name: Grab casacore tarball
  get_url:
    url: "https://github.com/casacore/casacore/archive/v{{casacore_version}}.tar.gz"
    dest: "{{casalibs_repo_dir}}/casacore-v{{casacore_version}}.tar.gz"
  register: casacore_tarball

- name: Unpack casacore tarball
  unarchive:
    copy: no
    src: "{{ casacore_tarball.dest }}"
    dest: "{{casalibs_repo_dir}}/"
    creates: "{{casalibs_repo_dir}}/casacore-{{casacore_version}}"
  register: casacore_checkout

#- name: Debug
#  debug: msg="{{casacore_checkout}}"

- name: Create casacore build-dir
  file:
    path: "{{casalibs_repo_dir}}/casacore-{{casacore_version}}/build"
    state: directory
  register: casacore_build_dir

#- name: Debug
#  debug: msg="{{casacore_build_dir}}"



- name: Configure casacore cmake build
  command: >
            cmake ..  -DCMAKE_INSTALL_PREFIX={{casacore_install_prefix}} \
              -DDATA_DIR={{casa_measures_datadir.path}} \
              -DUSE_HDF5=ON \
              -DUSE_THREADS=ON \
              -DBUILD_PYTHON=ON \
  args:
    chdir: "{{ casacore_build_dir.path }}"
  when: casacore_build_dir|changed
  register: casacore_cmake
  #Ignore errors so we can cleanup the build-dir if this fails:
  ignore_errors: True

- name: Do casacore make install
  shell: "make install -j{{ansible_processor_cores}} > make_install_stdout.log"
  args:
    chdir: "{{ casacore_build_dir.path }}"
  when: casacore_build_dir|changed
  register: casacore_make_install
  ignore_errors: True


- name: Clean up failed build
  file: path="{{ casacore_build_dir.path }}" state=absent
  when: casacore_cmake|failed or casacore_make_install|failed

- name: Fail a broken build
  fail: msg "Casacore build failed"
  when:  casacore_cmake|failed or casacore_make_install|failed

