- hosts: casalibsvm

  vars:
    casacore_version: "2.0.1"
    casarest_svn_rev: "8765"
    python_casacore_version: "2.0.0"
    casalibs_repo_dir: "/opt/repos"
    casalibs_install_prefix: "/opt/soft/casalibs"

    #Leave the venv setting undefined if you're just using PYTHONPATH:
#    python_casacore_venv: "{{casalibs_install_prefix}}/pycasacore-{{python_casacore_version}}-venv"
    #Should the virtualenv inherit system Python site-packages?
    python_casacore_venv_site_packages: False

    # Probably no need to change the rest of these:
    casacore_install_prefix: "{{casalibs_install_prefix}}/casacore-{{casacore_version}}"
    casarest_install_prefix: "{{casalibs_install_prefix}}/casarest-r{{casarest_svn_rev}}"
    casalibs_apt_deps: "{{ lookup('file', 'files/casalibs-apt-deps.txt').split() }}"
    python_casacore_packagedir: "{{casalibs_install_prefix}}/pycasacore-{{python_casacore_version}}-packagedir"

  tasks:
    - include: tasks/base.yml tags=base

    - name: Install apt dependencies.
      sudo: yes
      apt: name={{item}} update_cache=yes cache_valid_time=600
      with_items: casalibs_apt_deps
      tags: base

    - name: Create repo dir with correct permissions
      file: path={{item}} state=directory mode=0755 owner={{ansible_user_id}}
      with_items:
        - "{{ casalibs_repo_dir }}"
        - "{{ casalibs_install_prefix }}"
      sudo: yes

    - include: tasks/casa_measures.yml tags=casa_measures
    - include: tasks/casacore.yml tags=casacore
    - include: tasks/casarest.yml tags=casarest
    - include: tasks/python-casacore.yml tags=python-casacore

    - include: tasks/python-casacore-venv.yml tags=python-casacore
      when: python_casacore_venv is defined

    - name: Upload script to add casacore / casacore-python to path.
      template:
        src: templates/init-casalibs.sh
        dest: "{{casalibs_install_prefix}}/init-casalibs.sh"
        mode: 'ugo+r'
      tags: scripts

    - name: Check everything is working OK
      shell: >
              . {{casalibs_install_prefix}}/init-casalibs.sh &&
                python -c "from casacore import measures,tables; print('A-OK');"
      changed_when: False
      tags: test
